### ISSUE TITLE
system independent installation with dependencies

### ISSUE THREAD

**Issue by mzaiss** [KerstinHut/pypulseq-cest#12]
can 
```
pip install pypulseq 
pip install pyYAML
```
be added to the readme text?

easy_install pySimPulseqSBB-**1.0**.win-amd64-py3.7.exe  there is only version 0.1 here. hard to see. maybe rename.

it took me a while to install without swig and without git
cant we make a "windows precompiled installation" script that  downloads the zips and unzips them and also installs the precompiled exe? the version coudl be asked via prompt. would mak life easier for dumb windows user like me.

Is swig needed if the precompiled exe is used?

after I installed everything manually the install script approved:
"pySimPulseqSBB already installed. You can start your simulations."
after fixing issue with matplotlib everything works fine.

**Comment by KerstinHut** [comment]
We will work on an easy install that includes the dependencies. Until then, I changed the readme prerequisites and will include pip install hints.

**Comment by KerstinHut** [comment]
Dependency installation is now implemented. I will close this issue. If you encounter any problems, feel free to reopen it or open a new issue.
