### ISSUE TITLE
mpl.use('TkAgg')  necessary?

### ISSUE THREAD

**Issue by mzaiss** [KerstinHut/pypulseq-cest#13]
I got an import error in spyder
> ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'qt5' is currently running

it should be noted that the graphics output should be set to TKinter, this removed the error for me.
Howvere:  the code got stuck then. Couldnt resolve it until I commented in sequence.py the line

`7:  # mpl.use('TkAgg')`

Is this necessary or can this be removed, as it crashed everything for me.
Then maybe also tkinter is not needed

**Comment by schuenke** [comment]
I struggled with that on Friday as well when I wanted to use pypulseq in a QT5-based GUI. As it is pypulseq (and not pypulseq-cest) specific, we need to open an issue in pypulseq. I can do that. For the moment just comment out the line (that worked for me) or set it to the framewort you need. In your case it would be `mpl.use('qt')` I guess.

**Comment by KerstinHut** [comment]
I will close this issue as it is moved to pypulseq.
