### ISSUE TITLE
example seq file or plotting of it gives misleading Zpectra

### ISSUE THREAD

**Issue by mzaiss** [KerstinHut/pypulseq-cest#14]
The MTRasym of the example file looks weird, because it is not evauated around 0 but shifted by one offset due to M0 scan.
I would reccomend to make two plots, one with raw Z-spectrum only.
And one with normalized Z-spectrum and MTRasym correctly evaluated.
Otherwise people will see weird high cest efeftcs around 0 ppm and dismiss it.

also the yaml file uses  a superlorentz at -2 ppm
That leads to another artifact as the Superlorentz has a weird pole and shoudl only be used at 0 ppm.

### MT pool
mt_pool: {
  f: 0.1,
  r1: 1 / 1.3,
  r2: 1e5,
  k: 23,
  **dw: -2,**
  lineshape: 'SuperLorentzian'
}

**Comment by KerstinHut** [comment]
Thank you for the hint with the MT pool. I forgot about the plot issue. I should have a correct plot function in my other project, so I will try to adapt it to suit this one.

**Comment by KerstinHut** [comment]
Better plot function coming with the next merge, so I will close this issue.
