### ISSUE TITLE
t1 and t2 in sim file

### ISSUE THREAD

**Issue by kherz** [KerstinHut/pypulseq-cest#16]
I think it would be nice if we could set relaxation values as T1 and T2 in the simulation yaml files. I would like to use the yaml files in a c++ project and it's a little bit tricky to read fractions there. 
If we could define r1: 1/1.3 as t1: 1.3 instead that would be nice. 
I implemented that in the MATLAB version already (you can set either r1 or t1 / r2 or t2), so you might want to do the same for the python library.

**Comment by KerstinHut** [comment]
I updated that in the bmc tool, so functionality for the library should be ensured with t1 and t2 from the next update of bmc tool
