### ISSUE TITLE
renaming master to main

### ISSUE THREAD

**Issue by KerstinHut** [KerstinHut/pypulseq-cest#18]
To prevent the confusion with newer repos, I would like to rename the master in this repo to main. 
Any objections? @mzaiss  @kherz  @schuenke 
It will probably not affect you at all, apart from that you might be prompted once that there is no master, so you'll have to pull the main.

**Comment by schuenke** [comment]
fine for me 👍
maybe merge and delete all other branches before?! Not sure if it might be problematic for the auto-merge otherwise

**Comment by KerstinHut** [comment]
I renamed master to main.

Please use the following commands next time you fetch this  repo:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
```

@schuenke @mzaiss @kherz  @hnargos

**Comment by schuenke** [comment]
Worked for me. Thanks for providing the commands 👍
