### ISSUE TITLE
compilation on ubuntu fails

### ISSUE THREAD

**Issue by kherz** [KerstinHut/pypulseq-cest#19]
python setup.py faisl on ubuntu with g++ with the error

SimulationParameters.h:199:18: error: extra qualification ‘SimulationParameters::’ on member GetFinalMagnetizationVectors’ [-fpermissive]
  199 |  Eigen::MatrixXd SimulationParameters::GetFinalMagnetizationVectors();

**Comment by kherz** [comment]
found the issue. Fixed in PR #20

**Comment by KerstinHut** [comment]
This seems to work fine. Merging.
