### ISSUE TITLE
installation on ubuntu fails

### ISSUE THREAD

**Issue by kherz** [KerstinHut/pypulseq-cest#21]
The installation with the install.py script fails on ubuntu for me because of the denied permissions.
sudo is also not really an option here as installations with pip go into the user installation which means they dont exist for root.
We could fix this by replacing 
        check_install = subprocess.call([sys.executable, 'setup.py', 'install'], cwd=sim_path)
in the install.py script (line 29) with
        check_install = subprocess.call([sys.executable, 'setup.py', 'install', '--user'], cwd=sim_path)

Any objections?

**Comment by KerstinHut** [comment]
If I try to install into a virtual environment, this does not work for me. 
I found that 
`python install.py --user`
does the same for me as using your tag in the setup.py
Is this true for you also? If so, we could refer to that option in the readme and have the user decide.

**Comment by kherz** [comment]
No, that doesn't work. It's never recognized in the sim_setup function, is it?
I think we need to parse additional options in the main function of the install.py and pass that to the sim_setup funtion. So sth. like this in main:

```
str_options = ''
if len(sys.argv) > 1:
        str_options = str(sys.argv[1])
...
    sim_setup(sim_path=sim_path, setup_filepath=setup_filepath, str_options=str_options)
```

and this in sim_setup

```
def sim_setup(sim_path: Union[str, Path], setup_filepath: Union[str, Path], str_options):
...
        if not str_options:
            check_install = subprocess.call([sys.executable, 'setup.py', 'install'], cwd=sim_path)
        else:
            check_install = subprocess.call([sys.executable, 'setup.py', 'install', str_options], cwd=sim_path)
```

Then you could call the function with --user and without

**Comment by KerstinHut** [comment]
This works for me but I have no idea how to check if it does anything. Did you try it? You can find it in the 'paper' branch.

**Comment by kherz** [comment]
i can install it with the --user flag

**Comment by KerstinHut** [comment]
Perfect, thanks for testing!
