### ISSUE TITLE
simulate.py fails on ubuntu

### ISSUE THREAD

**Issue by kherz** [KerstinHut/pypulseq-cest#22]
After running 
`python install.py`
I tried
`python simulyte.py`
but I got the error
`undefined symbol: omp_get_thread_num`

I guess this is due to the fact that the -fopenmp flag is set in the sim/src/compile/setup.py file but the library is not linked.
There is no openmp code anyways, is it? So can the flag just be removed?

If we need it, we also need to take care of the fact that the Visual Studio Compiler has a different openmp flag.

**Comment by KerstinHut** [comment]
We don't seem to need it, I deleted the flag
